repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.1
  hooks:
   - id: ruff-check
     args: [ --fix ]
   - id: ruff-format

- repo: local
  hooks:
   - id: mypy
     name: mypy
     entry: mypy
     language: system
     types: [python]
     pass_filenames: false
     args: [src/valanga]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
   - id: trailing-whitespace
   - id: end-of-file-fixer
   - id: check-yaml
   - id: check-added-large-files
   - id: check-merge-conflict
